# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo
    container_name: mongodb-teste
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: admin
      TZ: America/Campo_Grande
